# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-07 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('barcode', models.IntegerField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=25)),
                ('product_manufacturer', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category_name', models.CharField(max_length=50)),
                ('stock_quantity', models.IntegerField(max_length=99999)),
            ],
        ),
        migrations.AddField(
            model_name='barcode',
            name='product_name',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
