# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-08 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(null=True),
        ),
    ]
