# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-07 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='barcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='stock_quantity',
            field=models.IntegerField(),
        ),
    ]
