# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-15 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170507_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
                ('category_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField()),
                ('product_date', models.DateField()),
                ('product_price', models.IntegerField()),
                ('product_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('product_price', models.IntegerField()),
                ('product_barcode', models.IntegerField()),
                ('product_stock', models.BooleanField()),
                ('product_date', models.DateField()),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='product_name',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
        migrations.DeleteModel(
            name='Barcode',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
