# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-16 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170515_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='product_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
