# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-08 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170608_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
