# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-16 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170516_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='product_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_stock',
            field=models.BooleanField(choices=[('IS', 'In Stock'), ('OS', 'Out of Stock')], default='IS'),
        ),
    ]
