# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-20 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170608_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_count',
            field=models.IntegerField(null=True),
        ),
    ]
