# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-17 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170516_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category_type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
