# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-18 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_items_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='product_status',
            field=models.BooleanField(choices=[('COLLECTED', 'Collected'), ('PROCESSING', 'Processing')], default='COLLECTED'),
        ),
    ]
