# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-18 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170518_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='product_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_stock',
            field=models.BooleanField(default=True),
        ),
    ]
